version: '3.8'

services:
  app:
    build: .
    container_name: bank-account_container
    ports:
      - "3000:3000"
    environment:
      - PORT=${PORT}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_CLUSTER_URL=${MONGO_CLUSTER_URL}
      - MONGO_DATABASE_NAME=${MONGO_DATABASE_NAME}
      - AUTH_SECRET_KEY=${AUTH_SECRET_KEY}
